/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_iredbyte_ndk_example_stepik_storage_Stepik */

#ifndef _Included_com_github_iredbyte_ndk_example_stepik_storage_Stepik
#define _Included_com_github_iredbyte_ndk_example_stepik_storage_Stepik
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_iredbyte_ndk_example_stepik_storage_Stepik
 * Method:    helloWord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_iredbyte_ndk_1example_stepik_storage_Stepik_helloWord
  (JNIEnv *, jobject);

/*
 * Class:     com_github_iredbyte_ndk_example_stepik_storage_Stepik
 * Method:    power
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_iredbyte_ndk_1example_stepik_storage_Stepik_power
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_github_iredbyte_ndk_example_stepik_storage_Stepik
 * Method:    powerRecursion
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_iredbyte_ndk_1example_stepik_storage_Stepik_powerRecursion
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_github_iredbyte_ndk_example_stepik_storage_Stepik
 * Method:    max3
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_github_iredbyte_ndk_1example_stepik_storage_Stepik_max3
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_github_iredbyte_ndk_example_stepik_storage_Stepik
 * Method:    log2
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_github_iredbyte_ndk_1example_stepik_storage_Stepik_log2
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_github_iredbyte_ndk_example_stepik_storage_Stepik
 * Method:    quadraticEquation
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_iredbyte_ndk_1example_stepik_storage_Stepik_quadraticEquation
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_github_iredbyte_ndk_example_stepik_storage_Stepik
 * Method:    rotate
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_github_iredbyte_ndk_1example_stepik_storage_Stepik_rotate
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_github_iredbyte_ndk_example_stepik_storage_Stepik
 * Method:    strcat
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_iredbyte_ndk_1example_stepik_storage_Stepik_strcat
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
