/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_iredbyte_ndk_example_storage_Stepik */

#ifndef _Included_com_github_iredbyte_ndk_example_storage_Stepik
#define _Included_com_github_iredbyte_ndk_example_storage_Stepik
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_iredbyte_ndk_example_storage_Stepik
 * Method:    helloWord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_iredbyte_ndk_1example_storage_Stepik_helloWord
  (JNIEnv *, jobject);

/*
 * Class:     com_github_iredbyte_ndk_example_storage_Stepik
 * Method:    power
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_iredbyte_ndk_1example_storage_Stepik_power
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_github_iredbyte_ndk_example_storage_Stepik
 * Method:    power_recursion
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_iredbyte_ndk_1example_storage_Stepik_power_1recursion
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_github_iredbyte_ndk_example_storage_Stepik
 * Method:    max3
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_github_iredbyte_ndk_1example_storage_Stepik_max3
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_github_iredbyte_ndk_example_storage_Stepik
 * Method:    log2
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_github_iredbyte_ndk_1example_storage_Stepik_log2
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_github_iredbyte_ndk_example_storage_Stepik
 * Method:    quadratic_equation
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_iredbyte_ndk_1example_storage_Stepik_quadratic_1equation
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
