/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_iredbyte_ndk_example_ndkman_storage_NdkMan */

#ifndef _Included_com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
#define _Included_com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
 * Method:    getCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_iredbyte_ndk_1example_ndkman_storage_NdkMan_getCount
  (JNIEnv *, jobject);

/*
 * Class:     com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_iredbyte_ndk_1example_ndkman_storage_NdkMan_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
 * Method:    setString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_iredbyte_ndk_1example_ndkman_storage_NdkMan_setString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
 * Method:    getInteger
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_github_iredbyte_ndk_1example_ndkman_storage_NdkMan_getInteger
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
 * Method:    setInteger
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_github_iredbyte_ndk_1example_ndkman_storage_NdkMan_setInteger
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
 * Method:    getBoolean
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_iredbyte_ndk_1example_ndkman_storage_NdkMan_getBoolean
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
 * Method:    setBoolean
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_github_iredbyte_ndk_1example_ndkman_storage_NdkMan_setBoolean
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
 * Method:    getFloat
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_iredbyte_ndk_1example_ndkman_storage_NdkMan_getFloat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
 * Method:    setFloat
 * Signature: (Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_com_github_iredbyte_ndk_1example_ndkman_storage_NdkMan_setFloat
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
 * Method:    getDouble
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_github_iredbyte_ndk_1example_ndkman_storage_NdkMan_getDouble
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
 * Method:    setDouble
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_github_iredbyte_ndk_1example_ndkman_storage_NdkMan_setDouble
  (JNIEnv *, jobject, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
