/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_iredbyte_ndk_example_storage_Stepik */

#ifndef _Included_com_github_iredbyte_ndk_example_storage_Stepik
#define _Included_com_github_iredbyte_ndk_example_storage_Stepik
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_iredbyte_ndk_example_storage_Stepik
 * Method:    helloWord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_iredbyte_ndk_1example_storage_Stepik_helloWord
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
