/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_iredbyte_ndk_example_ndkman_storage_NdkMan */

#ifndef _Included_com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
#define _Included_com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
 * Method:    getCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_iredbyte_ndk_1example_ndkman_storage_NdkMan_getCount
  (JNIEnv *, jobject);

/*
 * Class:     com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_iredbyte_ndk_1example_ndkman_storage_NdkMan_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_github_iredbyte_ndk_example_ndkman_storage_NdkMan
 * Method:    setString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_iredbyte_ndk_1example_ndkman_storage_NdkMan_setString
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
